[package]
name = "kakashi_vault"
version = "0.1.0"
description = "Kakashi Swap: Innovative StarkNet DEX with Cairo 1.0, revolutionizing decentralized trading"
homepage = "https://github.com/bacharif/kakashi"

[scripts]
test = "protostar test"
gen-project = "sh scripts/generate_cairo_project.sh"
test-cairo = "cairo-test --starknet ."
test-devnet = "npm test"

[dependencies]
starknet = ">=1.1.0"
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
openzeppelin = {git = "https://github.com/enitrat/cairo-contracts", branch = "cairo-1"}

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
# Enable CASM codegen.
casm = true
name = "compiled"
